---

platform: linux

image_resource:
  type: docker-image
  source: {repository: rjain/buildbox}

inputs:
  - name: product

run:
  path: bash
  args:
  - "-c"
  - |
    set -e

    GOVC_CMD=govc

    FILE_PATH=`find ./product/ -name *.ova`

    $GOVC_CMD import.spec $FILE_PATH > import-spec.json

    yq e import-spec.json

    rm import-spec*
