---
platform: linux

inputs:
- name: env

params:
  ENV_FILE: env.yml
  # - Filepath of the env config YAML
  # - Relative to root of the `env` input
  PRODUCT_NAMES:

run:
  path: bash
  args:
  - "-c"
  - |
    OPTIONS=""

    IFS=',' read -ra PRODUCTS <<< "$PRODUCT_NAMES"
    for i in "${PRODUCTS[@]}"; do
      OPTIONS+=" --product-name $i"
    done
    
    om --env env/"${ENV_FILE}" apply-changes --ignore-warnings ${OPTIONS}
