#@data/values
---
env:
separate_config: False
pivnet_token: ((pivnet_token))
git:
  username: ((git_credentials.username))
  token: ((git_credentials.password))
  automation_git_url: https://github.com/rahulkj/pcf-automation
  automation_git_branch: master
  config_repo_git_url: https://github.com/rahulkj/secrets
  config_repo_git_branch: master
  locks_git_url: https://github.com/rahulkj/pipeline-locks
  locks_git_branch: master
  lock_folder: pipeline-lock
credhub:
  prefix: concourse/homelab
  ca_cert: ((credhub_server_ca.certificate))
  client: ((credhub_client))
  client_secret: ((credhub_client_secret))
  server: ((credhub_server))
smtp:
  address: ((smtp_address))
  port: ((smtp_port))
  username: ((smtp_credentials.username))
  password: ((smtp_credentials.password))
  from_address: ((from_address))
  to_addresses: ((to_addresses))
s3:
  endpoint: http://((s3_endpoint))/
  access_key: ((s3_credentials.username))
  secret_key: ((s3_credentials.password))
  disable_ssl: true
configs:
  apply_changes_config_filename: deploy-products.yml
  opsman_config_filename: opsman-config.yml
  director_config_filename: director-config.yml
  env_filename: env.yml
  state_file_destination: state-files
vars:
  folder: vars
  opsman_var_filename: opsman.yml
  opsman_auth_filename: opsman-auth.yml
  director_var_filename: director.yml
iaas: vsphere
opsman_backup_bucket: ((s3_opsman_backup_bucket))
attempts: 3
products:
- name: ops-manager
  slug: ops-manager
  glob: '*.ova'
  version: ^2\.9\.[0-9]*$
  s3_bucket: opsman
  s3_product_regex: "ops-manager-vsphere-(2.9.*).ova"
  has_stemcell: False
  deploy_product: False
  is_opsman: True
  is_platform_automation: False
  authentication: ldap            # possible values: internal|ldap|saml
- name: pks
  slug: pivotal-container-service
  glob: '*.pivotal'
  version: ^1\.8\.[0-9]*$
  s3_bucket: pks  
  has_stemcell: True
  stemcell_version: "621"
  s3_stemcell_bucket: stemcells
  s3_product_regex: "pivotal-container-service-(1.8.*).pivotal"
  deploy_product: True
  is_opsman: False
  is_platform_automation: False
- name: platform-automation-image
  slug: platform-automation
  glob: '*.tgz'
  version: ^4\.4\..*$
  s3_bucket: automation
  s3_product_regex: image/platform-automation-image-(4.4.*).tgz
  has_stemcell: False
  deploy_product: False
  is_opsman: False
  is_platform_automation: True
- name: platform-automation-tasks
  slug: platform-automation
  glob: '*.zip'
  version: ^4\.4\..*$
  s3_bucket: automation
  s3_product_regex: tasks/platform-automation-tasks-(4.4.*).zip
  has_stemcell: False
  deploy_product: False
  is_opsman: False
  is_platform_automation: True
- name: harbor
  slug: harbor-container-registry
  glob: "*.pivotal"
  version: ^1\.10\.[0-9]*$
  s3_bucket: harbor
  has_stemcell: True
  stemcell_version: "456"
  s3_stemcell_bucket: stemcells
  s3_product_regex: "harbor-container-registry-(1.10.*).pivotal"
  deploy_product: True
  is_opsman: False
  is_platform_automation: False
- name: pas
  slug: elastic-runtime
  glob: 'cf-*.pivotal'
  version: ^2\.9\.[0-9]*$
  s3_bucket: pas
  has_stemcell: True
  stemcell_version: "621"
  s3_stemcell_bucket: stemcells
  s3_product_regex: "cf-(2.9.*).pivotal"
  deploy_product: False
  is_opsman: False
  is_platform_automation: False
- name: nsx-t
  slug: vmware-nsx-t
  glob: 'VMware-NSX-T-*.pivotal'
  version: ^3\.0\.[0-9]*$
  s3_bucket: nsx-t
  has_stemcell: False
  s3_product_regex: "VMware-NSX-T-(3.0.*).pivotal"
  deploy_product: False
  is_opsman: False
  is_platform_automation: False
