resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

resources:
- name: schedule
  type: time
  source:
    interval: 24h
    start: "12:00 AM"
    stop: "11:59 PM"
    location: America/Los_Angeles
    days: [Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday]

- name: tile-config-convertor
  type: github-release
  source:
    user: rahulkj
    repository: tile-config-convertor
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: config-repo
  type: git
  source:
    uri: ((config_repo_git_url))
    branch: ((config_repo_git_branch))
    username: ((git_username))
    password: ((git_token))

- name: automation-repo
  type: git
  source:
    uri: ((automation_git_url))
    branch: ((automation_git_branch))
    username: ((git_username))
    password: ((git_token))

- name: platform-automation-image
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((platform_automation_version))
    sort_by: semver

- name: product
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ((product_slug))
    product_version: ((product_version))

- name: platform-automation-tasks
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: platform-automation
    product_version: ((platform_automation_version))
    sort_by: semver

- name: custom-docker-image
  type: docker-image
  source:
    repository: rjain/buildbox

- name: locks
  type: pool
  source:
    pool: ((lock_folder))
    uri: ((locks_git_url))
    branch: ((locks_git_branch))
    username: ((git_username))
    password: ((git_token))

- name: email
  type: email
  source:
    smtp:
      host: ((smtp_address))
      port: ((smtp_port))
      username: ((smtp_username))
      password: ((smtp_password))
    from: ((from_address))
    to: [((to_addresses))]

credhub-interpolate: &credhub-interpolate-env
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  input_mapping:
    files: config-repo
  output_mapping:
    interpolated-files: env
  params:
    PREFIX: ((credhub_prefix))
    CREDHUB_CA_CERT: ((credhub_ca_cert))
    CREDHUB_CLIENT: ((credhub_client))
    CREDHUB_SECRET: ((credhub_client_secret))
    CREDHUB_SERVER: ((credhub_server))
    INTERPOLATION_PATHS: ((opsman_env_path))

credhub-interpolate: &credhub-interpolate-vars
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  input_mapping:
    files: config-repo
  output_mapping:
    interpolated-files: vars
  params:
    PREFIX: ((credhub_prefix))
    CREDHUB_CA_CERT: ((credhub_ca_cert))
    CREDHUB_CLIENT: ((credhub_client))
    CREDHUB_SECRET: ((credhub_client_secret))
    CREDHUB_SERVER: ((credhub_server))
    INTERPOLATION_PATHS: ((product_vars_path))
    SKIP_MISSING: true

cli-params: &cli-params
  params:
    globs:
    - "*linux*64*"

jobs:
- name: scheduler
  plan:
  - get: schedule
    trigger: true
  - get: product
    params:
      globs: []

- name: set-lock
  plan:
  - get: product
    params:
      globs: []
    passed: [scheduler]
    trigger: true
  - put: locks
    params: {acquire: true}

- name: upload-and-stage-product
  serial: true
  plan:
  - in_parallel:
    - get: config-repo
    - get: automation-repo
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
    - get: product
      params:
        globs: [((product_glob))]
      passed: [set-lock]
      trigger: true
    - get: custom-docker-image

  - task: create-opsman-env-file
    <<: *credhub-interpolate-env

  - in_parallel:
    - task: upload-and-stage-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-and-stage-product.yml
      input_mapping:
        product: product
        env: env
      params:
        ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

    - task: download-stemcell
      image: custom-docker-image
      file: automation-repo/tasks/download-stemcell/task.yml
      input_mapping:
        product: product
      params:
        PIVNET_API_TOKEN: ((pivnet_token))
        IAAS_TYPE: ((iaas_type))
        STEMCELL_TYPE: ((stemcell_type))

  - task: upload-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      stemcell: stemcells
      env: env
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))

- name: generate-config
  plan:
  - in_parallel:
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
    - get: automation-repo
    - get: config-repo
    - get: pivnet-product
      resource: product
      params:
        globs: []
      passed: [upload-and-stage-product]
    - get: tile-config-convertor
      <<: *cli-params
    - get: custom-docker-image

  - task: create-opsman-env-file
    <<: *credhub-interpolate-env

  - task: generate-config
    image: custom-docker-image
    file: automation-repo/tasks/generate-config/task.yml
    input_mapping:
      git-repo: automation-repo
      env: env
      config: config-repo
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      CONFIG_FILE: ((product_config_path))/((product_config_filename))

- name: configure-product
  serial: true
  plan:
  - in_parallel:
    - get: config-repo
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
    - get: product
      params:
        globs: []
      trigger: true
      passed: [upload-and-stage-product]

  - task: create-opsman-env-file
    <<: *credhub-interpolate-env

  - task: create-product-var-files
    <<: *credhub-interpolate-vars

  - task: config-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: config-repo
      env: env
      vars: vars
    params:
      CONFIG_FILE: ((product_config_path))/((product_config_filename))
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      VARS_FILES: ((vars_folder))/((product_vars_path))/((product_var_filename))

- name: deploy-product
  serial: true
  plan:
  - in_parallel:
    - get: config-repo
    - get: automation-repo
    - get: platform-automation-image
      params:
        globs: ["*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      params:
        globs: ["*.zip"]
        unpack: true
    - get: product
      params:
        globs: []
      trigger: true
      passed: [configure-product]

  - task: create-opsman-env-file
    <<: *credhub-interpolate-env

  - task: deploy-product
    file: automation-repo/tasks/apply-changes.yml
    input_mapping:
      env: env
      config: config-repo
    params:
      ENV_FILE: ((opsman_env_path))/((opsman_env_filename))
      APPLY_CHANGES_CONFIG: ((product_config_path))/((apply_changes_config_filename))
    attempts: ((attempts))

  - put: email
    params:
      subject_text: "Build finished: ${BUILD_PIPELINE_NAME}/${BUILD_JOB_NAME}/${BUILD_NAME}"
      body_text: "Build finished: ${ATC_EXTERNAL_URL}/teams/main/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"

- name: release-lock
  plan:
  - in_parallel:
    - get: locks
    - get: product
      params:
        globs: []
      passed: [deploy-product]
      trigger: true
  - put: locks
    params: {release: locks}

- name: unset-lock
  plan:
  - get: locks
  - put: locks
    params: {release: locks}
